[package]
description = "A git wrapper"
edition = "2021"
homepage = "https://rit.mazylol.com"
license-file = "LICENSE"
name = "rit-mazy"
readme = "README.md"
repository = "https://github.com/mazylol/rit"
version = "0.1.6"

[[bin]]
name = "rit"
path = "src/main.rs"
